services:
  migrations:
    image: ${DOCKER_USERNAME}/pawnshop-api:latest
    network_mode: "host"
    env_file: .env
    volumes:
      - /srv/logs:/srv/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: "no"
    command: migration:run:prod

  api:
    image: ${DOCKER_USERNAME}/pawnshop-api:latest
    network_mode: "host"
    env_file: .env
    volumes:
      - /srv/logs:/srv/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
    command: start:server:prod
    depends_on:
      - migrations

  web:
    image: ${DOCKER_USERNAME}/pawnshop-web:latest
    ports:
      - "4001:80"
    restart: unless-stopped
    depends_on:
      - api
